#ifndef SAW_WAVETABLE_H
#define SAW_WAVETABLE_H

#include <cstdint>

#define WAVETABLE_SIZE 2048
#define NUM_OCTAVE_BANDS 11

namespace synth {

// Band-limited sawtooth wavetables, one per octave band.
// Generated by scripts/generate_tables.py using additive synthesis.
// Each band includes only harmonics below Nyquist for its frequency range.
extern const int16_t sawWavetable[NUM_OCTAVE_BANDS][WAVETABLE_SIZE];

// Maps MIDI note (0–127) to the appropriate octave band index (0–10).
extern const uint8_t noteToOctaveBand[128];

} // namespace synth

#endif // SAW_WAVETABLE_H
