#!/usr/bin/env python3
"""
Generate precomputed lookup tables for the supersaw synth.

This script calculates:
1. midiNotePhaseInc[128] - Phase increments for MIDI notes 0-127
2. detuneMultiplier[7] - Detune multipliers for 7 oscillators
3. sawWavetable[11][2048] - Band-limited sawtooth wavetables (one per octave band)
4. noteToOctaveBand[128] - MIDI note to octave band mapping

Usage:
    python3 scripts/generate_tables.py
"""

import math
import os

SAMPLE_RATE = 44100
NUM_OSCILLATORS = 7
WAVETABLE_SIZE = 2048
NUM_OCTAVE_BANDS = 11


def compute_phase_inc(note: int) -> int:
    """
    Compute phase increment for a MIDI note.
    phase_inc = freq / SAMPLE_RATE * 2^32
    freq = 440 * 2^((note - 69) / 12)
    """
    freq = 440.0 * pow(2.0, (note - 69) / 12.0)
    return int(freq / SAMPLE_RATE * 4294967296.0)


def compute_detune_multiplier(index: int) -> int:
    """
    Compute detune multiplier in Q16.16 fixed-point.
    Oscillator order: [-3/3, -2/3, -1/3, 0, +1/3, +2/3, +3/3] * 0.3 semitones
    multiplier = 2^(offset * 0.3 / 12), stored as (multiplier * 65536)
    """
    offset = (index - 3) / 3.0  # range -1.0 to +1.0
    semitones = offset * 0.3
    mult = pow(2.0, semitones / 12.0)
    return int(mult * 65536.0 + 0.5)


def midi_note_freq(note: int) -> float:
    """Return the frequency in Hz for a MIDI note number."""
    return 440.0 * pow(2.0, (note - 69) / 12.0)


def compute_wavetable(band: int) -> list[int]:
    """
    Compute a band-limited sawtooth wavetable for the given octave band.
    Uses additive synthesis: saw(x) = sum( (-1)^(k+1) * sin(k*x) / k ) * 2/pi
    Harmonics are limited to those below Nyquist for the highest note in the band.
    """
    # Highest MIDI note in this band
    highest_note = min((band + 1) * 12 - 1, 127)
    highest_freq = midi_note_freq(highest_note)
    nyquist = SAMPLE_RATE / 2.0
    max_harmonic = max(1, int(nyquist / highest_freq))

    table = [0.0] * WAVETABLE_SIZE
    for k in range(1, max_harmonic + 1):
        sign = 1.0 if (k % 2 == 1) else -1.0
        amplitude = sign / k
        for n in range(WAVETABLE_SIZE):
            table[n] += amplitude * math.sin(2.0 * math.pi * k * n / WAVETABLE_SIZE)

    # Normalize: scale so peak amplitude matches naive saw range (±16383).
    # The naive oscillator produces values in [-16384, +16383] via (phase >> 17) - 16384,
    # so wavetables must target the same amplitude to avoid a loudness jump at the crossover.
    peak = max(abs(v) for v in table) if table else 1.0
    if peak == 0.0:
        peak = 1.0
    scale = 16383.0 / peak
    return [max(-16384, min(16383, int(v * scale + (0.5 if v >= 0 else -0.5)))) for v in table]


def compute_note_to_band() -> list[int]:
    """Map each MIDI note (0–127) to its octave band index."""
    return [min(note // 12, NUM_OCTAVE_BANDS - 1) for note in range(128)]


def generate_wavetable_file(output_path: str):
    """Generate the saw_wavetable.cpp file with band-limited wavetable data and phase increments."""
    lines: list[str] = []
    lines.append('#include "synth/saw_wavetable.h"')
    lines.append("")
    lines.append("namespace synth {")
    lines.append("")

    # Generate phase increments
    lines.append("// Precomputed phase increments for MIDI notes 0–127.")
    lines.append("// phase_inc = freq / SAMPLE_RATE * 2^32")
    lines.append("// freq = 440 * 2^((note - 69) / 12)")
    lines.append("const uint32_t midiNotePhaseInc[128] = {")
    phase_incs = [compute_phase_inc(note) for note in range(128)]
    for i in range(0, 128, 4):
        vals = phase_incs[i : i + 4]
        lines.append("    " + ", ".join(f"{v:10d}" for v in vals) + ",")
    lines.append("};")
    lines.append("")

    # Generate wavetables
    lines.append("// Band-limited sawtooth wavetables, one per octave band.")
    lines.append("// Generated by additive synthesis with harmonics limited to Nyquist.")
    lines.append(
        f"const int16_t sawWavetable[{NUM_OCTAVE_BANDS}][{WAVETABLE_SIZE}] = {{"
    )
    for band in range(NUM_OCTAVE_BANDS):
        highest_note = min((band + 1) * 12 - 1, 127)
        highest_freq = midi_note_freq(highest_note)
        max_harm = max(1, int((SAMPLE_RATE / 2.0) / highest_freq))
        lines.append(f"    // Band {band}: notes {band * 12}–{highest_note},"
                     f" max harmonic = {max_harm}")
        lines.append("    {")
        table = compute_wavetable(band)
        for i in range(0, WAVETABLE_SIZE, 16):
            chunk = table[i : i + 16]
            lines.append("        " + ", ".join(f"{v:6d}" for v in chunk) + ",")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    # Generate note-to-band mapping
    note_to_band = compute_note_to_band()
    lines.append("// Maps MIDI note (0–127) to octave band index.")
    lines.append(f"const uint8_t noteToOctaveBand[128] = {{")
    for i in range(0, 128, 16):
        chunk = note_to_band[i : i + 16]
        lines.append("    " + ", ".join(f"{v:2d}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace synth")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {output_path}")


def main():
    # Generate band-limited wavetable file
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    output_path = os.path.join(project_root, "src", "synth", "saw_wavetable.cpp")
    generate_wavetable_file(output_path)


if __name__ == "__main__":
    main()
