#!/usr/bin/env python3
"""
Generate the pitch-bend frequency-ratio lookup table.

Pitch bend multiplies the base phase increment by a frequency ratio:
    ratio = 2 ^ (semitoneOffset / 12)

The table covers a symmetric range of +/- MAX_SEMITONES semitones at a
resolution of STEPS_PER_SEMITONE entries per semitone, so the synth never
has to compute an exponential at runtime (the RP2040 has no FPU). At runtime
the bend value (14-bit, 0..16383, centre 8192) and the configurable bend
range (in semitones) are combined with integer math to index this table.

Output format: Q16.16 unsigned (65536 = unity / no bend).

Usage:
    python3 scripts/generate_pitchbend_table.py          # write header file
"""

import os


MAX_SEMITONES = 24        # +/- range covered by the table (2 octaves)
STEPS_PER_SEMITONE = 32   # resolution (~3.1 cents per step)
Q = 16                    # Q16.16 fixed-point


CENTER_INDEX = MAX_SEMITONES * STEPS_PER_SEMITONE
TABLE_SIZE = 2 * CENTER_INDEX + 1


def compute_pitchbend_table() -> list[int]:
    """Return TABLE_SIZE Q16.16 frequency ratios for +/- MAX_SEMITONES."""
    table = []
    for k in range(TABLE_SIZE):
        semitones = (k - CENTER_INDEX) / STEPS_PER_SEMITONE
        ratio = pow(2.0, semitones / 12.0)
        table.append(int(ratio * (1 << Q) + 0.5))
    return table


def format_table(table: list[int]) -> str:
    """Format the table as a C uint32_t array initialiser."""
    lines = []
    for i in range(0, len(table), 6):
        chunk = table[i : i + 6]
        lines.append("    " + ", ".join(f"{v:7d}" for v in chunk) + ",")
    return "\n".join(lines)


def write_header(table: list[int]):
    """Write the pitch-bend table as a C header file."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    header_path = os.path.join(project_root, "src", "synth", "pitchbend_table.h")

    content = (
        "#ifndef PITCHBEND_TABLE_H\n"
        "#define PITCHBEND_TABLE_H\n"
        "\n"
        "#include <cstdint>\n"
        "\n"
        "namespace synth {\n"
        "\n"
        "// Pitch-bend frequency-ratio lookup table (Q16.16: 65536 = unity).\n"
        "// ratio = 2 ^ (semitoneOffset / 12), tabulated over\n"
        f"// +/- {MAX_SEMITONES} semitones at {STEPS_PER_SEMITONE} steps/semitone.\n"
        "// Generated by scripts/generate_pitchbend_table.py - do not edit.\n"
        f"inline constexpr int32_t PITCHBEND_MAX_SEMITONES = {MAX_SEMITONES};\n"
        f"inline constexpr int32_t PITCHBEND_STEPS_PER_SEMITONE = {STEPS_PER_SEMITONE};\n"
        f"inline constexpr int32_t PITCHBEND_CENTER_INDEX = {CENTER_INDEX};\n"
        f"inline constexpr int32_t PITCHBEND_TABLE_SIZE = {TABLE_SIZE};\n"
        "\n"
        f"inline constexpr uint32_t pitchBendRatioTable[{TABLE_SIZE}] = {{\n"
        f"{format_table(table)}\n"
        "};\n"
        "\n"
        "} // namespace synth\n"
        "\n"
        "#endif // PITCHBEND_TABLE_H\n"
    )

    with open(header_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {header_path}")

    # Print diagnostics for a few reference points.
    print(f"\n// Pitch-bend ratio reference (Q16.16, 65536 = unity):")
    for st in (-MAX_SEMITONES, -12, -4, -1, 0, 1, 4, 12, MAX_SEMITONES):
        idx = st * STEPS_PER_SEMITONE + CENTER_INDEX
        print(f"//   {st:+3d} st -> {table[idx]:7d}  ({table[idx] / 65536.0:.4f}x)")


def main():
    table = compute_pitchbend_table()
    write_header(table)


if __name__ == "__main__":
    main()
