#!/usr/bin/env python3
"""
Generate the logarithmic MIDI velocity-to-gain lookup table.

The curve uses a power function to match human loudness perception,
with a minimum gain floor so soft notes remain audible:
    gain = MIN_GAIN + (1 - MIN_GAIN) × (velocity / 127) ^ 0.4

This gives finer dynamic control at low velocities and a compressed
range at high velocities — the standard "logarithmic" MIDI velocity
response used by most hardware synthesizers.

Output format: Q8 unsigned (0–256, where 256 = unity gain).

Usage:
    python3 scripts/generate_velocity_table.py          # write header file
"""

import os


EXPONENT = 0.4
SCALE = 256  # Q8: 256 = 1.0
MIN_GAIN = 0.30  # minimum gain floor (30%) for velocity 1


def compute_velocity_table() -> list[int]:
    """Return 128 Q8 gain values for the logarithmic velocity curve."""
    table = [0]  # velocity 0 = silent
    for v in range(1, 128):
        # Map through power curve, then scale into [MIN_GAIN .. 1.0] range
        normalized = pow(v / 127.0, EXPONENT)
        gain = (MIN_GAIN + (1.0 - MIN_GAIN) * normalized) * SCALE
        table.append(max(1, int(gain + 0.5)))
    return table


def format_table(table: list[int]) -> str:
    """Format the table as a C uint16_t array initialiser."""
    lines = []
    for i in range(0, 128, 8):
        chunk = table[i : i + 8]
        lines.append("    " + ", ".join(f"{v:3d}" for v in chunk) + ",")
    return "\n".join(lines)


def write_header(table: list[int]):
    """Write the velocity table as a C header file."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    header_path = os.path.join(project_root, "src", "synth", "velocity_table.h")

    content = (
        "#ifndef VELOCITY_TABLE_H\n"
        "#define VELOCITY_TABLE_H\n"
        "\n"
        "#include <cstdint>\n"
        "\n"
        "namespace synth {\n"
        "\n"
        "// Logarithmic MIDI velocity-to-gain lookup table (Q8: 256 = unity).\n"
        f"// Curve: gain = ({MIN_GAIN} + {1.0 - MIN_GAIN:.2f} × (velocity / 127) ^ {EXPONENT}) × {SCALE}\n"
        "// Generated by scripts/generate_velocity_table.py — do not edit.\n"
        "static const uint16_t velocityGainTable[128] = {\n"
        f"{format_table(table)}\n"
        "};\n"
        "\n"
        "} // namespace synth\n"
        "\n"
        "#endif // VELOCITY_TABLE_H\n"
    )

    with open(header_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {header_path}")

    # Print diagnostics
    print(f"\n// Velocity → gain mapping (Q8, {SCALE} = unity):")
    for v in range(128):
        pct = table[v] * 100.0 / SCALE
        print(f"//   vel {v:3d} → gain {table[v]:3d}  ({pct:5.1f}%)")


def main():
    table = compute_velocity_table()
    write_header(table)


if __name__ == "__main__":
    main()
