#!/usr/bin/env python3
"""
Generate the allpass interpolation coefficient lookup table for the stereo chorus.

The chorus uses allpass interpolation for sub-sample delay:
    a = (256 - frac) * 256 / (256 + frac)       (Q8)

where frac is the fractional delay part (0–255).  On Cortex-M0+ a division
costs ~50–70 cycles, so pre-computing the 256 entries into a lookup table
saves ~100–140 cycles per stereo sample pair.

Usage:
    python3 scripts/generate_chorus_table.py          # print table to stdout
    python3 scripts/generate_chorus_table.py --write   # patch chorus.cpp in-place
"""

import argparse
import os
import re


def compute_allpass_table() -> list[int]:
    """Return 256 Q8 allpass interpolation coefficients."""
    table = []
    for f in range(256):
        coeff = round((256 - f) * 256 / (256 + f))
        table.append(coeff)
    return table


def format_table(table: list[int]) -> str:
    """Format the table as a C uint16_t array initialiser."""
    lines = []
    for i in range(0, 256, 16):
        chunk = table[i : i + 16]
        lines.append("    " + ", ".join(f"{v:3d}" for v in chunk) + ",")
    return "\n".join(lines)


def print_table(table: list[int]):
    """Print the C table and diagnostic info to stdout."""
    print("// Precomputed allpass interpolation coefficients (256 entries, Q8).")
    print("// allpassCoeffTable[f] = round((256 - f) * 256 / (256 + f))")
    print("static const uint16_t allpassCoeffTable[256] = {")
    print(format_table(table))
    print("};")
    print()
    print(f"// Entries: {len(table)}")
    print(f"// Range: {min(table)}–{max(table)}")


def patch_chorus_cpp(table: list[int]):
    """Replace the allpass coefficient table in chorus.cpp in-place."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    chorus_cpp = os.path.join(project_root, "src", "synth", "chorus.cpp")

    with open(chorus_cpp, "r", encoding="utf-8") as f:
        content = f.read()

    # Build replacement block
    comment = (
        "// Precomputed allpass interpolation coefficients (256 entries, Q8).\n"
        "// allpassCoeffTable[f] = round((256 - f) * 256 / (256 + f)) "
        "for f = 0..255.\n"
        "// Replaces a per-sample integer division (~50\u201370 cycles on M0+) "
        "with a table\n"
        "// lookup (~2 cycles). Stored in flash (512 bytes).\n"
        "// Generated by scripts/generate_chorus_table.py \u2014 do not edit."
    )
    array_body = format_table(table)
    replacement = (
        f"{comment}\n"
        f"static const uint16_t allpassCoeffTable[256] = {{\n"
        f"{array_body}\n"
        f"}};"
    )

    # Match comment block + table declaration
    pattern = (
        r"//[^\n]*allpass[^\n]*coeffi[^\n]*\n"   # first comment line
        r"(?://[^\n]*\n)*"                        # additional comment lines
        r"static const uint16_t allpassCoeffTable\[256\]\s*=\s*\{[^}]+\};"
    )
    new_content, count = re.subn(pattern, replacement, content, flags=re.IGNORECASE)
    if count == 0:
        print("ERROR: Could not find allpassCoeffTable in", chorus_cpp)
        return

    with open(chorus_cpp, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Patched {chorus_cpp} ({count} replacement(s))")


def main():
    parser = argparse.ArgumentParser(
        description="Generate allpass interpolation coefficient LUT for chorus."
    )
    parser.add_argument(
        "--write", action="store_true",
        help="Patch the table directly into src/synth/chorus.cpp"
    )
    args = parser.parse_args()

    table = compute_allpass_table()

    if args.write:
        patch_chorus_cpp(table)
    else:
        print_table(table)


if __name__ == "__main__":
    main()
