#!/usr/bin/env python3
"""
Generate the piecewise-exponential filter cutoff coefficient table.

The curve is split into two segments for finer control at high frequencies:
  - CC   0–80:  20 Hz  →  8 kHz  (exponential, ~8.6 octaves in 81 steps)
  - CC  80–127:  8 kHz → 16 kHz  (exponential,  1   octave  in 47 steps)

This gives roughly 5× more resolution in the top octave compared to a
single exponential spanning the full range.

Each table entry stores: tan(π × fc / SAMPLE_RATE) × 2^14  (Q14)
which is the cutoff coefficient fed directly into the ZDF trapezoidal SVF.

Usage:
    python3 scripts/generate_filter_table.py          # print table to stdout
    python3 scripts/generate_filter_table.py --write  # generate src/synth/filter_cutoff_table.h
"""

import argparse
import math
import os

SAMPLE_RATE = 44100

# Piecewise breakpoints
CC_BREAK = 80          # CC index where segments join
FREQ_MIN = 20.0        # Hz at CC 0
FREQ_BREAK = 8000.0    # Hz at CC_BREAK
FREQ_MAX = 16000.0     # Hz at CC 127


def compute_cutoff_table() -> list[int]:
    """Return 128 Q14 cutoff coefficients for the piecewise-exponential curve."""
    table = []
    for cc in range(128):
        if cc <= CC_BREAK:
            # Segment 1: exponential from FREQ_MIN to FREQ_BREAK
            t = cc / CC_BREAK
            fc = FREQ_MIN * pow(FREQ_BREAK / FREQ_MIN, t)
        else:
            # Segment 2: exponential from FREQ_BREAK to FREQ_MAX
            t = (cc - CC_BREAK) / (127 - CC_BREAK)
            fc = FREQ_BREAK * pow(FREQ_MAX / FREQ_BREAK, t)
        # fc never exceeds FREQ_MAX (16000 Hz), which is well below Nyquist
        # (SAMPLE_RATE / 2 = 22050 Hz), so no clamp is needed.
        coeff = math.tan(math.pi * fc / SAMPLE_RATE) * 16384.0
        table.append(max(1, int(coeff + 0.5)))
    return table


def format_table(table: list[int]) -> str:
    """Format the table as a C int32_t array initialiser."""
    lines = []
    for i in range(0, 128, 8):
        chunk = table[i : i + 8]
        lines.append("    " + ", ".join(f"{v:5d}" for v in chunk) + ",")
    return "\n".join(lines)


def print_table(table: list[int]):
    """Print the C table and some diagnostic info to stdout."""
    print(f"// Piecewise-exponential cutoff coefficients (Q14):")
    print(f"//   CC   0–{CC_BREAK}:  {FREQ_MIN:.0f} Hz → {FREQ_BREAK:.0f} Hz")
    print(f"//   CC {CC_BREAK}–127: {FREQ_BREAK:.0f} Hz → {FREQ_MAX:.0f} Hz")
    print(f"// coeff = tan(π × fc / {SAMPLE_RATE}) × 16384")
    print("inline constexpr int32_t filterCutoffTable[128] = {")
    print(format_table(table))
    print("};")
    print()

    # Diagnostics: show frequency at each CC
    print("// CC → frequency mapping:")
    for cc in range(128):
        if cc <= CC_BREAK:
            t = cc / CC_BREAK
            fc = FREQ_MIN * pow(FREQ_BREAK / FREQ_MIN, t)
        else:
            t = (cc - CC_BREAK) / (127 - CC_BREAK)
            fc = FREQ_BREAK * pow(FREQ_MAX / FREQ_BREAK, t)
        print(f"//   CC {cc:3d} → {fc:8.1f} Hz  (coeff = {table[cc]})")


def write_header(table: list[int]):
    """Generate src/synth/filter_cutoff_table.h with the computed table."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    output_path = os.path.join(project_root, "src", "synth", "filter_cutoff_table.h")

    comment = (
        f"// Piecewise-exponential cutoff coefficients (Q14):\n"
        f"//   CC   0–{CC_BREAK}:  {FREQ_MIN:.0f} Hz → {FREQ_BREAK:.0f} Hz  "
        f"(exponential)\n"
        f"//   CC {CC_BREAK}–127: {FREQ_BREAK:.0f} Hz → {FREQ_MAX:.0f} Hz  "
        f"(exponential, finer resolution)\n"
        f"// coeff = tan(π × fc / {SAMPLE_RATE}) × 16384"
    )
    array_body = format_table(table)

    content = (
        f"// AUTO-GENERATED by scripts/generate_filter_table.py — DO NOT EDIT\n"
        f"#ifndef FILTER_CUTOFF_TABLE_H\n"
        f"#define FILTER_CUTOFF_TABLE_H\n"
        f"\n"
        f"#include <cstdint>\n"
        f"\n"
        f"namespace synth {{\n"
        f"\n"
        f"{comment}\n"
        f"inline constexpr int32_t filterCutoffTable[128] = {{\n"
        f"{array_body}\n"
        f"}};\n"
        f"\n"
        f"}} // namespace synth\n"
        f"\n"
        f"#endif // FILTER_CUTOFF_TABLE_H\n"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate piecewise-exponential filter cutoff LUT."
    )
    parser.add_argument(
        "--write", action="store_true",
        help="Generate src/synth/filter_cutoff_table.h"
    )
    args = parser.parse_args()

    table = compute_cutoff_table()

    if args.write:
        write_header(table)
    else:
        print_table(table)


if __name__ == "__main__":
    main()
